# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(498, 611)
        self.Umowacheckbox = QtWidgets.QCheckBox(parent=Dialog)
        self.Umowacheckbox.setGeometry(QtCore.QRect(90, 270, 200, 20))
        self.Umowacheckbox.setObjectName("Umowacheckbox")
        self.PeselLine = QtWidgets.QLineEdit(parent=Dialog)
        self.PeselLine.setGeometry(QtCore.QRect(210, 230, 202, 22))
        self.PeselLine.setInputMask("")
        self.PeselLine.setObjectName("PeselLine")
        self.pese = QtWidgets.QLabel(parent=Dialog)
        self.pese.setGeometry(QtCore.QRect(90, 220, 90, 38))
        self.pese.setObjectName("pese")
        self.NumerLine = QtWidgets.QLineEdit(parent=Dialog)
        self.NumerLine.setGeometry(QtCore.QRect(210, 190, 202, 22))
        self.NumerLine.setInputMask("")
        self.NumerLine.setObjectName("NumerLine")
        self.numer = QtWidgets.QLabel(parent=Dialog)
        self.numer.setGeometry(QtCore.QRect(90, 180, 101, 38))
        self.numer.setObjectName("numer")
        self.NazwiskoLine = QtWidgets.QLineEdit(parent=Dialog)
        self.NazwiskoLine.setGeometry(QtCore.QRect(210, 150, 202, 22))
        self.NazwiskoLine.setObjectName("NazwiskoLine")
        self.nazwisko = QtWidgets.QLabel(parent=Dialog)
        self.nazwisko.setGeometry(QtCore.QRect(90, 140, 90, 38))
        self.nazwisko.setObjectName("nazwisko")
        self.ImieLine = QtWidgets.QLineEdit(parent=Dialog)
        self.ImieLine.setGeometry(QtCore.QRect(210, 110, 202, 22))
        self.ImieLine.setObjectName("ImieLine")
        self.imie = QtWidgets.QLabel(parent=Dialog)
        self.imie.setGeometry(QtCore.QRect(90, 100, 90, 38))
        self.imie.setObjectName("imie")
        self.test = QtWidgets.QLabel(parent=Dialog)
        self.test.setGeometry(QtCore.QRect(80, 500, 331, 31))
        self.test.setText("")
        self.test.setObjectName("test")
        self.listWidget = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget.setGeometry(QtCore.QRect(110, 390, 256, 111))
        self.listWidget.setObjectName("listWidget")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(100, 330, 291, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ZapiszButton = QtWidgets.QPushButton(parent=self.widget)
        self.ZapiszButton.setObjectName("ZapiszButton")
        self.horizontalLayout.addWidget(self.ZapiszButton)
        self.ZapiszdoplikuButton = QtWidgets.QPushButton(parent=self.widget)
        self.ZapiszdoplikuButton.setObjectName("ZapiszdoplikuButton")
        self.horizontalLayout.addWidget(self.ZapiszdoplikuButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Umowacheckbox.setText(_translate("Dialog", "Umowa o pracę"))
        self.pese.setText(_translate("Dialog", "Pesel"))
        self.numer.setText(_translate("Dialog", "Numer Telefonu"))
        self.nazwisko.setText(_translate("Dialog", "Nazwisko"))
        self.imie.setText(_translate("Dialog", "Imie"))
        self.ZapiszButton.setText(_translate("Dialog", "Zapisz"))
        self.ZapiszdoplikuButton.setText(_translate("Dialog", "Zapisz do pliku "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
